name: Deploy Azure MLZ to the ARPA-H Tenant

on:
    workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        #enable-AzPSSession: true

    - name: Deploy Bicep file for MLZ
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        # subscriptionId: ${{ secrets.AZURE_SUB_ID }}
        region: eastus2
        #deploymentMode: 'Validate'
        template: ./src/bicep/mlz-arpah.bicep
        parameters: ./src/bicep/parameters/mlz-arpah.parameters.json
        failOnStdErr: false